//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenClientPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketEntry2
    {
        public int TicketID { get; set; }
        public string Header { get; set; }
        public string TicDescription { get; set; }
        public Nullable<int> TicStatus { get; set; }
    }
}
