//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenClientPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZenClientTicketEntities1 : DbContext
    {
        public ZenClientTicketEntities1()
            : base("name=ZenClientTicketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TicketEntry> TicketEntries { get; set; }
        public virtual DbSet<TicketEntry1> TicketEntry1 { get; set; }
        public virtual DbSet<TicketEntry2> TicketEntry2 { get; set; }
    }
}
